import React, { useEffect, useRef } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import Banner from "@/components/Banner";
import About from "@/components/About";
import Work from "@/components/Work";
import Stacks from "@/components/Stacks";
import Footer from "@/components/Footer";
import styles from "../styles/Home.module.css";
import { projects, works } from "@/data";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log(projects.stacks, "test");
  console.log(works[0], "nih")

  return (
    <>
      <Head>
        <title>Sherly Lolita Sari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <About />

        <div id="professional-portfolio" className={styles.titleWork}>Professional Portfolio</div>
        <div className={styles.headerbarWork}></div>

        {works.map((work, i) => (
          <Work 
            key={i}
            id={work.id}
            title={work.title}
            description={work.description}
            thumbnail={work.image.thumbnail}
            screenshoots={work.image.screenshoots}
            demo={work.link}
          /> 
        ))}
        

        
        <Stacks stacks={projects.stacks} />
        <Footer />
      </main>
    </>
  );
}
